### ISSUE TITLE
fetchSubjectSets tests sometimes timeout

### ISSUE THREAD

**Issue by srallen** [zooniverse/front-end-monorepo#2368]
Tests failed in an unrelated PR due to timeouts with the `fetchSubjectSets` helper:

https://github.com/zooniverse/front-end-monorepo/pull/2366/checks?check_run_id=3363343980#step:11:137

**Comment by eatyourgreens** [comment]
I don't know if these are related, but there are random timeouts in the classifier tests too. Could these all be tests that use `nock` to mock the API?

```
  2402 passing (2m)
  9 pending
  2 failing

  1) Component > FieldGuideWrapper
       when the field guide is shown
         "before each" hook for "should display the FieldGuide based on the showModal prop":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/odonnell/zooniverse/front-end-monorepo/packages/lib-classifier/src/components/Classifier/components/FieldGuide/FieldGuideWrapper.spec.js)
      at processImmediate (internal/timers.js:456:21)

  2) Component > BarChartViewer
       Background
         "before all" hook for "should render":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/odonnell/zooniverse/front-end-monorepo/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/BarChartViewer/BarChartViewer.spec.js)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by eatyourgreens** [comment]
Seeing an occasional failure of the UPP tests too. Should be easy to fix.
```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[When@41460]'
ReferenceError: done is not defined
    at /home/runner/work/front-end-monorepo/front-end-monorepo/packages/lib-classifier/src/store/UserProjectPreferencesStore.spec.js:227:11
```

**Comment by eatyourgreens** [comment]
Another timeout, while running CI for #2385.
https://github.com/zooniverse/front-end-monorepo/pull/2385/checks?check_run_id=3409113331#step:11:814

I can't see anything in common across the failing tests. Maybe something in test setup that's timing out?

**Comment by eatyourgreens** [comment]
#2361 fixes a missing mock in the subject picker tests, but I'm not sure how that would be related (if at all) to the random timeouts here.

**Comment by eatyourgreens** [comment]
Another timeout, in the survey task tests, while checking #2385 locally.

```
  2409 passing (2m)
  9 pending
  2 failing

  1) Component > Choice
       with choice with images, confusions, and questions
         should render Questions:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/odonnell/zooniverse/front-end-monorepo/packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/Choice.spec.js)
      at processImmediate (internal/timers.js:456:21)

  2) Component > Questions
       with hasFocus of true
         should have the first question's first input as the document active element:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/odonnell/zooniverse/front-end-monorepo/packages/lib-classifier/src/plugins/tasks/SurveyTask/components/components/Choice/components/Questions/Questions.spec.js)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by goplayoutside3** [comment]
This timeout hasn't happened recently, especially link to `fetchSubjectSets` so I'm going to close. Please feel free to open again if timeout becomes a problem.
