### ISSUE TITLE
Pure ES Modules break the Mocha tests

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#3779]
WHAT?? The tests for `app-project` and `lib-classifier` are failing on:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/shaun/projects/front-end-monorepo/node_modules/d3/src/index.js from /Users/shaun/projects/front-end-monorepo/packages/app-project/src/shared/components/ProjectStatistics/components/CompletionBar/CompletionBar.js not supported.
Instead change the require of index.js in /Users/shaun/projects/front-end-monorepo/packages/app-project/src/shared/components/ProjectStatistics/components/CompletionBar/CompletionBar.js to a dynamic import() which is available in all CommonJS modules.
```

and

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/shaun/projects/front-end-monorepo/node_modules/d3/src/index.js from /Users/shaun/projects/front-end-monorepo/packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js not supported.
Instead change the require of index.js in /Users/shaun/projects/front-end-monorepo/packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js to a dynamic import() which is available in all CommonJS modules.
```

and etc

OK, so upon review:
- _D3 now ships as pure ES modules and requires Node.js 12 or higher._ - this IS a problem.

Additional reading:
- [The awkward valley to ESM: Node.js, Victory, and D3](https://formidable.com/blog/2022/victory-esm/) - 15 Jun 2022, formidable.com - TL;DR: as more libraries (e.g. d3.js) drop CommonJS support and go 100% ESM (ECMAScript Modules), a lot of upstream/downstream dependencies that use CommonJS get borked. (ESM setups can read ESM + CommonJS modules, but CommonJS setups can't read ESModules.) Awkward transpiling workarounds are required.
- [Importing Issues - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module](https://github.com/d3/d3-array/issues/218) - 29 Jun 2021, D3 repo - TL;DR: [lol good luck](https://github.com/d3/d3-array/issues/218#issuecomment-870600490)
- [import conflict with 3.0.0 update](https://github.com/d3/d3-format/issues/114) - 25 Apr 2021, D3 repo - TL;DR: [lol not a d3 problem, fix your NextJS](https://github.com/d3/d3-format/issues/114#issuecomment-826338584)
  - Yeah, but lib-classifier has the same error, and it's not running Next.JS. Also, I think our tests aren't running Next.JS?

### Status

🤷 throw_hands_up_emoji

Good gravy, I need to check with the other devs to see if anybody else has encountered the ESM import issues. I might have missed something someone on the team is already aware of, since this doesn't seem to be a niche problem.

_Originally posted by @shaunanoordin in https://github.com/zooniverse/front-end-monorepo/issues/3361#issuecomment-1171274486_

**Comment by eatyourgreens** [comment]
Why our Mocha tests are using CommonJS to require modules, I do not know. Some Babel config rewriting `import` as `require`?

**Comment by eatyourgreens** [comment]
We could try adding `regenerator-runtime/runtime` to the Mocha config. 
https://stackoverflow.com/a/60522428

**Comment by eatyourgreens** [comment]
We could also try publishing the libraries as ES Modules, but need to be mindful of not breaking Zoo Notes or Mapping Viz.

**Comment by eatyourgreens** [comment]
[Mocha Babel examples](https://github.com/mochajs/mocha-examples/tree/master/packages/babel) might be useful.

**Comment by eatyourgreens** [comment]
#3900 adds ES modules to `@zooniverse/classifier` and `@zooniverse/react-components`, alongside the UMD modules built by webpack. Builds and deploys use the ES modules. Mocha tests require the UMD modules. 

#3920 converts `@zooniverse/async-states`, which is a single JS file, from CommonJS to ES6. Builds that use it run fine, but tests fail for both NextJS apps and the classifier, when they try to `require` the ES module.

**Comment by eatyourgreens** [comment]
#4064 removed the webpack UMD builds. The classifier and Zooniverse React Components are published as ESM, for the NextJS builds, and CommonJS for the Mocha tests.

**Comment by eatyourgreens** [comment]
`@zooniverse/panoptes-js` also uses `require` and `module.exports` (CommonJS.)

**Comment by eatyourgreens** [comment]
Shaun's ESM notes here are very useful. 

https://github.com/zooniverse/community-catalog/issues/165

**Comment by eatyourgreens** [comment]
`next-i18next` breaks if you convert the config file to ES6. 
- https://github.com/i18next/next-i18next/issues/2185

There may be a workaround. See the conversation on that issue.

**Comment by eatyourgreens** [comment]
Bun has a good explanation of Node module resolution and the differences between CommonJS and ESM. 

https://bun.sh/docs/runtime/modules

**Comment by eatyourgreens** [comment]
Node now has experimental support for `require(esm)`. 

https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/

**Comment by eatyourgreens** [comment]
`require(esm)` is now default behaviour in Node 23. 🎉

https://nodejs.org/en/blog/release/v23.0.0

I think you can enable it with a flag in Node 22, which should be LTS now.

**Comment by eatyourgreens** [comment]
[How to convert CommonJS to ESM](https://deno.com/blog/convert-cjs-to-esm), just published yesterday.

**Comment by eatyourgreens** [comment]
If you switch to Node 22, then `yarn bootstrap` and `yarn test` both fail 😞. I discovered that by accident today, when I forgot to switch back from Node 22 to Node 20 while building the monorepo.

**Comment by eatyourgreens** [comment]
`require(esm)` is also available in Node 20.17, behind the `experimental-require-modules` flag. That should allow you to upgrade packages without having to upgrade Node.

**Comment by goplayoutside3** [comment]
I was investigating this mocha config x ESM issue yesterday and want steer this Github discussion toward potential solutions for the monorepo, ideally without completely change our testing architecture.

Please correct me if I'm wrong, but in summary:
- FEM's mocha config uses `@babel/register` to transpile. The purpose of babel is to transpile your js code to an understandable version of js for the given tool you're using. Mocha does not understand JSX, so in FEM babel is a must.
- Third-party package maintainers are moving toward ESM-only, which is fine for building and running the Next.js apps, or Storybook in the browser, but throws `Error [ERR_REQUIRE_ESM]: require() of ES Module [third-party package] from [FEM component] not supported`. For example: [mime v4 in lib-content's unit tests](https://github.com/zooniverse/front-end-monorepo/actions/runs/11170387365/job/31053112946?pr=6265#step:9:51).
- Mocha [can work](https://mochajs.org/#nodejs-native-esm-support) with ESM-only. This requires `type: module` in the package.json.
    - I experimented with adding `type: module` to lib-content, ensuring no `require()` syntax in the library code, and even excluding its `jsdom` setup file. However, this config results in the problem documented [here](https://gist.github.com/smhg/9e75eee75818e09f99011e565340f45f) where I saw `Unexpected token '<'` thrown on the first `.spec.js` file. `babel/register` does _not_ support compiling native Node.js ES modules on the fly (bottom of their docs [here](https://babeljs.io/docs/babel-register#compiling-plugins-and-presets-on-the-fly)).
    - At this point, I'm not sure if this shortcoming of `@babel/register` is a complete blocker to FEM's architecture of React + Babel + Mocha.

@eatyourgreens you've left a few comments with potential solutions. Did you try any of these combos?
- The `--experimental-require-module flag` with Node v20
- Node v22 with `type: module` in a library?

**Comment by eatyourgreens** [comment]
I just ran a very quick experiment with Node 22:

```sh
nvm use 22
yarn install --ignore-scripts
yarn bootstrap
```

The project app build fails with:
```sh
unhandledRejection TypeError: Cannot set properties of undefined (setting 'eio')
    at /Users/jimodonnell/zooniverse/front-end-monorepo/node_modules/panoptes-client/lib/SugarClient/primus.js:3805:9
    at Array.<anonymous> (/Users/jimodonnell/zooniverse/front-end-monorepo/node_modules/panoptes-client/lib/SugarClient/primus.js:3806:3)
    at UMDish (/Users/jimodonnell/zooniverse/front-end-monorepo/node_modules/panoptes-client/lib/SugarClient/primus.js:4:15)
    at Object.<anonymous> (/Users/jimodonnell/zooniverse/front-end-monorepo/node_modules/panoptes-client/lib/SugarClient/primus.js:11:3)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24) {
  type: 'TypeError'
}
```

**Comment by eatyourgreens** [comment]
One problem the monorepo has is that both JS and JSX files use the `.js` extension, so build tools would have to assume that every `.js` file is a JSX file and transpile to JS.

If you look at PFE, for example, I think JSX files use `.jsx` there. Changing all the file extensions for the monorepo doesn't seem practical, though.

**Comment by eatyourgreens** [comment]
Oh, looks like I already tried Node 22 back in October: https://github.com/zooniverse/front-end-monorepo/issues/3779#issuecomment-2438044257

**Comment by goplayoutside3** [comment]
> Oh, looks like I already tried Node 22 back in October:

Right, that's why I was curious if you'd tried Node v22 while also adjusting `type: module` in package.json files.

**Comment by eatyourgreens** [comment]
Removing the offending line, then running the `lib-content` tests again, gets us back to `unexpected token <` because JSX isn't JS.

```sh
@zooniverse/content:test
$ mocha --config ./test/.mocharc.json ./.storybook/specConfig.js "./src/**/*.spec.js"
      
       Exception during run: SyntaxError[ @/Users/jimodonnell/zooniverse/front-end-monorepo/packages/lib-content/.storybook/specConfig.js ]: Unexpected token '<'
          at compileSourceTextModule (node:internal/modules/esm/utils:340:16)
          at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
          at #translate (node:internal/modules/esm/loader:433:12)
          at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:480:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by eatyourgreens** [comment]
[Mocha tests containing JSX with ESM](https://gist.github.com/smhg/9e75eee75818e09f99011e565340f45f) suggests running Mocha with a custom Node loader, but I don't know how old that is or which versions of Node it was written for.

**Comment by eatyourgreens** [comment]
I have to confess that currently I use Storybook with Playwright to run tests for JSX components in a pure ESM project, and it just works out-of-the-box.

https://github.com/nismod/irv-jamaica/blob/83a31ea2e4a20b4a7ab42555b262b4af8894dfcc/.github/workflows/storybook-tests.yml#L19-L29

**Comment by eatyourgreens** [comment]
> I was investigating this mocha config x ESM issue yesterday and want steer this Github discussion toward potential solutions for the monorepo, ideally without completely change our testing architecture.

This seems like an excellent summary to me. I'd add a couple of points:
- Older packages like `lib-panoptes-js` were written before Node supported `import/export`, so are still using `require` and `module.exports`. This leads to CI errors in #6375, where browser code (`import/export`) exists alongside older Node code(`require/module exports`). Now that Node supports `import` and `export`, it might be worth taking some time to remove `require` and `module exports=` from all packages. That might require converting them from `type: commonjs` to `type: module`.
- Up until Node 20, `type: commonjs` is the default for any package that doesn't explicitly specify a type. The Node 22 module loader seems to dynamically determine a type, by inspecting a file for `import/export` syntax. This can lead to errors if a file uses ES6 syntax but doesn't run in strict mode. I'd suggest explicitly setting `type: commonjs` on all packages, until they've been converted to ESM.

**Comment by eatyourgreens** [comment]
> This looks similar to the hexoid error previously thrown by app-root that was fixed by using alias in the webpack config object in next.config.js.

The Sugar client is crashing here, when it adds `engine-io` to the window (or to the Primus client instance).

https://github.com/zooniverse/panoptes-javascript-client/blob/721b696dccecf86a35614244ab29d19d1a62c3b7/lib/SugarClient/primus.js#L3795-L3806

**Comment by eatyourgreens** [comment]
#3920 converted `lib-async-states` to ESM. It might be worth revisiting that with Node 20 or Node 22.

**Comment by goplayoutside3** [comment]
I've started to track the third-party libraries that cause tests to fail in the top level description of this Issue.

**Comment by eatyourgreens** [comment]
I tagged Dependabot PRs with ESM if they break the tests. I don’t know if that still happens.

**Comment by eatyourgreens** [comment]
[A deep dive into CommonJS and ES Modules in NodeJS](https://blog.appsignal.com/2024/12/11/a-deep-dive-into-commonjs-and-es-modules-in-nodejs.html).

**Comment by goplayoutside3** [comment]
Node 20.19 [enables require(esm) by default](https://nodejs.org/en/blog/release/v20.19.0#requireesm-is-now-enabled-by-default) and running `yarn test` for most of FEM's libraries fails with the error `unexpected token <`. Example [action](https://github.com/zooniverse/front-end-monorepo/actions/runs/13949756090/job/39045863767) run when `coverage.yml` uses Node v20.*

https://github.com/zooniverse/front-end-monorepo/pull/6773 shows that specifying Node v20.18 in `coverage.yml` results in passing tests.

**Comment by eatyourgreens** [comment]
For Node 20.19, you'll probably need to explicitly specify `type: commonjs` in all packages now.
