### ISSUE TITLE
Dev storybook errors on startup with 'mainConfigMatches is not iterable'

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/front-end-monorepo#5860]
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Discovered while working on #5857.

```
(base) asosxlap127:lib-classifier odonnell$ yarn storybook
yarn run v1.22.21
$ storybook dev -p 6006
@storybook/cli v7.6.8

TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:6:1094)
    at async loadMainConfig (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:19:6723)
    at async buildDevStandalone (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/core-server/dist/index.js:119:1186)
    at async withTelemetry (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/core-server/dist/index.js:65:3948)
    at async dev (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/cli/dist/generate.js:478:401)
    at async Command.<anonymous> (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/cli/dist/generate.js:493:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/cli/bin/index.js:23
  throw error;
  ^

TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (/Users/odonnell/zooniverse/front-end-monorepo/node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:6:1094)

Node.js v20.9.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce
Run `yarn storybook` from `packages/lib-classifier`.

## Expected behavior
The storybook should run without errors

## Additional context
Installed `@storybook` packages are a mixture of versions from 7.6.6 to 7.6.9. All installed `@storybook` packages must be on the same version, in order to run the storybook. Upgrading all packages to 7.6.9 should fix this.

**Comment by eatyourgreens** [comment]
#5861 fixed this for me. Cleaning the Yarn cache, and reinstalling, might also fix it (https://github.com/storybookjs/storybook/issues/24520#issuecomment-1771397125.)
